name: Cron
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '* * * * *'

jobs:
  job1:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: List files
      run: ls
