name: Slack cleanup

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron:  '*/15 * * * *'

jobs:
  clean_slack:
    runs-on: ubuntu-latest      
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: List files
      run: ls
    - name: Clean Slack
      run: python main.py
      env:
        SLACK_OAUTH_ACCESS_TOKEN: ${{ secrets.SLACK_OAUTH_ACCESS_TOKEN }}
